INSERT INTO `books` (`bookID`, `title`, `description`, `author`, `publisher`, `genre`, `year`, `language`, `price`, `isbn`, `inStock`, `newArrival`, `clearanceBook`, `premiumPick`, `imageFile`, `imageDirectory`) VALUES
(1, 'The Hobbit', 'Bilbo Baggins lives a quiet, peaceful life in his comfortable hole at Bag End. Bilbo lives in a hole because he is a hobbit, one of a race of small, plump people about half the size of humans, with furry toes and a great love of good food and drink. Bilbo is quite content at Bag End, near the bustling hobbit village of Hobbiton, but one day his comfort is shattered by the arrival of the old wizard Gandalf, who persuades Bilbo to set out on an adventure with a group of thirteen militant dwarves. The dwarves are embarking on a great quest to reclaim their treasure from the marauding dragon Smaug, and Bilbo is to act as their burglar. The dwarves are very skeptical about Gandalf choice for a burglar, and Bilbo is terrified to leave his comfortable life to seek adventure. But Gandalf assures both Bilbo and the dwarves that there is more to the little hobbit than meets the eye.', 'J. R. R. Tolkien', 'George Allen Unwin', 'Adventure, Fantasy, Mystery', 1937, 'English', 12, '978-0-26-110221-7', 2, 1, 0, 0, 'The Hobbit.png', 'C:\\xampp\\htdocs\\NewChapter\\uploads\\The Hobbit.png'),
(2, 'Crazy Rich Asians', 'Crazy Rich Asians is the outrageously funny debut novel about three super-rich, pedigreed Chinese families and the gossip, backbiting, and scheming that occurs when the heir to one of the most massive fortunes in Asia brings home his ABC (American-born Chinese) girlfriend to the wedding of the season.\r\n\r\nWhen Rachel Chu agrees to spend the summer in Singapore with her boyfriend, Nicholas Young, she envisions a humble family home, long drives to explore the island, and quality time with the man she might one day marry. What she doesn\'t know is that Nick\'s family home happens to look like a palace, that she\'ll ride in more private planes than cars, and that with one of Asia\'s most eligible bachelors on her arm, Rachel might as well have a target on her back.', 'Kevin Kwan', 'Knopf Doubleday Publishing Group', 'Comedy, Romance', 2017, 'English', 9, '978-0-52-556376-1', 1, 0, 0, 0, 'Crazy Rich Asians.png', 'C:\\xampp\\htdocs\\NewChapter\\uploads\\Crazy Rich Asians.png'),
(3, 'The Lord of the Rings', 'One Ring to rule them all, One Ring to find them, One Ring to bring them all and in the darkness bind them\r\n\r\nIn ancient times the Rings of Power were crafted by the Elven-smiths, and Sauron, the Dark Lord, forged the One Ring, filling it with his own power so that he could rule all others. But the One Ring was taken from him, and though he sought it throughout Middle-earth, it remained lost to him. After many ages it fell by chance into the hands of the hobbit Bilbo Baggins.\r\n\r\nFrom Sauron\'s fastness in the Dark Tower of Mordor, his power spread far and wide. Sauron gathered all the Great Rings to him, but always he searched for the One Ring that would complete his dominion.', 'J. R. R. Tolkien', 'Allen Unwin', 'Action, Adventure, Fantasy, Mystery', 1954, 'English', 11, '978-0-54-400341-5', 1, 0, 1, 0, 'The Lord of the Rings.png', 'C:\\xampp\\htdocs\\NewChapter\\uploads\\The Lord of the Rings.png'),
(4, 'Sixteen Horses', 'A literary thriller from stunning new talent Greg Buchanan, Sixteen Horses is a story of enduring guilt, trauma, and punishment, set in a small seaside community the rest of the world has left behind.\r\n\r\nIn Ilmarsh, England, local police detective Alec Nichols discovers sixteen horses\' heads on a farm, each buried with a single eye facing the low winter sun. After Veterinary Forensics expert Cooper Allen travels to the scene, a pathogen is discovered lurking within the soil, and many of those who have come into contact with the corpses grow critically ill.', 'Greg Buchanan', 'Flatiron Books', 'Action, Crime, Horror, Sci-fi', 2021, 'English', 8, '978-1-25-024667-7', 1, 1, 0, 0, 'Sixteen Horses.png', 'C:\\xampp\\htdocs\\NewChapter\\uploads\\Sixteen Horses.png'),
(5, 'On Food and Cooking', 'For its twentieth anniversary, Harold McGee prepared a new, fully revised and updated edition of On Food and Cooking. He has rewritten the text almost completely, expanded it by two-thirds, and commissioned more than 100 new illustrations. As compulsively readable and engaging as ever, the new On Food and Cooking provides countless eye-opening insights into food, its preparation, and its enjoyment.\r\n\r\nOn Food and Cooking pioneered the translation of technical food science into cook-friendly kitchen science and helped birth the inventive culinary movement known as molecular gastronomy. Though other books have been written about kitchen science, On Food and Cooking remains unmatched in the accuracy, clarity, and thoroughness of its explanations, and the intriguing way in which it blends science with the historical evolution of foods and cooking techniques.', 'Harold McGee', 'Scribner U.S. Hodder', 'Cooking', 1984, 'English', 7, '978-0-68-480001-1', 1, 0, 1, 0, 'On Food and Cooking.png', 'C:\\xampp\\htdocs\\NewChapter\\uploads\\On Food and Cooking.png'),
(6, 'The Cook You Want to Be', 'Andy Baraghani peeled hundreds of onions at Chez Panisse as a teenage intern, honed his perfectly balanced salad, making skills at Estela in New York, and developed recipes in the test kitchens of Saveur, Tasting Table, and Bon Appetit. It took him all those years to figure out the cook he wanted to be, a cook who is true to his Persian heritage, a fresh-vegetable lover, a citrus superfan, and an always-hungry world traveler. In The Cook You Want to Be, Baraghani shows home cooks on how to hone their own cooking styles by teaching the techniques and unexpected flavor combinations that maximize flavor in minimal time.', 'Andy Baraghani', 'Lorena Jones Books', 'Cooking', 2020, 'English', 13, '978-1-98-485856-6', 1, 0, 0, 1, 'The Cook You Want to Be.png', 'C:\\xampp\\htdocs\\NewChapter\\uploads\\The Cook You Want to Be.png'),
(7, 'Cik Delivery', 'Kisah cinta mereka bukanlah sehebat Romeo and Juliet. Bukan seromantis kisah Cinderella\r\napatah lagi seagung cinta Rasullullah dan Saidatina Khadijah. Namun, kisah cinta yang biasa-\r\nbiasa ini menjadi luar biasa bila ada ikatan rasa terhubung sebelum cinta. Menjadi isteri\r\nbelum waktunya kepada lelaki yang dia sendiri tak kenal. Walhal semuanya hanya drama\r\nsemata-mata.\r\nInara Mikayla menerima cinta pada waktu dia terpaksa memilih di antara cinta dan keluarga.\r\nSilapnya dia memilih cinta sehingga diketepikan oleh keluarga sendiri. Dia lemah bila dia\r\nterpaksa terima kehilangan cinta dan kehilangan keluarga. Namun, demi Aqil dia bangkit\r\nmenjadi seorang yang tabah dan sentiasa pandang ke depan.\r\nRiyadh Aryan, lelaki yang hidup dengan kesempurnaan. Dia ada segala-galanya tapi, jarang\r\nrasa cukup. Wasiat arwah papanya supaya dia berkahwin dengan anak Tan Sri Marzuki\r\nbukanlah mudah untuk dilaksanakan. Lagi serabut bila satu Malaysia tahu dia bakal menjadi\r\nmenantu Tan Sri Marzuki. Dia bukanlah takut nak kahwin tapi, dia takut dengan siapa dia\r\nnak kahwin.', 'Dyadila', 'Suara Hati', 'Documentary, History', 2020, 'Bahasa Melayu', 5, '978-9-67-230020-5', 1, 0, 1, 0, 'Cik Delivery.png', 'C:\\xampp\\htdocs\\NewChapter\\uploads\\Cik Delivery.png'),
(8, 'Biografi Tun Abdul Razak', 'Tun Abdul Razak, Perdana Menteri Malaysia kedua ialah arkitek utama dalam pembinaan negara-bangsa Malaysia. Ketika memimpin Malaysia, setelah terjadinya peristiwa 13 Mei 1969, beliau menyusun strategi serampang dua mata supaya negara mencapai pembangunan ekonomi yang pesat dan mantap serta memulakan langkah penyusunan semula struktur ekonomi dansosial masyarakat Malaysia yang berbilang-bilang kaum. Beliau memperkenalkan Rukun Negara dan Dasar Ekonomi Baru yang terbukti berjaya membantu proses pembangunan negara untuk jangka panjang.\r\n\r\n \r\n\r\nBuku ini memaparkan liku-liku kehidupan, perjuangan, visi, misi dan pengorbanan Tun Abdul Razak sebagai seorang negarawan dan patriot Malaysia. Antara tajuk penting yang dipaparkan dalam buku ini adalah: kelahiran seorang patriot, pengalaman di bawah pemerintahan Jepun, menimba ilmu di England, berjuang dalam UMNO, penggubalan Perlembagaan Persekutuan, pembentukan Malaysia, menangani konfrontasi Indonesia, Dasar Pelajaran Kebangsaan, Dasar Ekonomi Baru, politik permuafakatan Barisan Nasional dan banyak lagi. Kebanyakan nukilan dalam biografi ini ialah hasil penyelidikan dan pengumpulan maklumat yang komprehensif dan berwibawa oleh tiga tokoh akademik yang berpengalaman luas. Banyak perkara yang dinukilkan belum pernah diketahui umum sebelum ini.', 'Nik Anuar Nik Mahmud', 'Penerbit UKM', 'Biography', 2011, 'Bahasa Melayu', 12, '978-9-67-942948-0', 2, 0, 0, 1, 'Biografi Tun Abdul Razak.png', 'C:\\xampp\\htdocs\\NewChapter\\uploads\\Biografi Tun Abdul Razak.png'),
(9, 'Journey to the West', 'Journey to the West is a classic Chinese mythological novel. It was written during the Ming Dynasty based on traditional folktales. Consisting of 100 chapters, this fantasy relates the adventures of a Tang Dynasty (618-907) priest Sanzang and his three disciples, Monkey, Pig and Friar Sand, as they travel west in search of Buddhist Sutra. The first seven chapters recount the birth of the Monkey King and his rebellion against Heaven. Then in chapters eight to twelve, we learn how Sanzang was born and why he is searching for the scriptures, as well as his preparations for the journey. The rest of the story describes how they vanquish demons and monsters, tramp over the Fiery Mountain, cross the Milky Way, and after overcoming many dangers, finally arrive at their destination - the Thunder Monastery in the Western Heaven - and find the Sutra.', 'Wu Cheng\'en', 'University of Chicago Press', 'Adventure, Comedy, Fantasy', 2012, 'Chinese', 12, '978-7-11-901663-4', 3, 0, 0, 1, 'Journey to the West.png', 'C:\\xampp\\htdocs\\NewChapter\\uploads\\Journey to the West.png'),
(10, 'Life and Death in Shanghai', 'This is a first-hand account of China\'s cultural revolution. Nien Cheng, an anglophile and fluent English-speaker who worked for Shell in Shanghai under Mao, was put under house arrest by Red Guards in 1966 and subsequently jailed. All attempts to make her confess to the charges of being a British spy failed; all efforts to indoctrinate her were met by a steadfast and fearless refusal to accept the terms offered by her interrogators. When she was released from prison she was told that her daughter had committed suicide. In fact Meiping had been beaten to death by Maoist revolutionaries.', 'Cheng Nien', 'Penguin Books', 'Biography, Documentary, History', 2010, 'Chinese', 12, '978-0-80-214516-1', 2, 0, 0, 1, 'Life and Death in Shanghai.png', 'C:\\xampp\\htdocs\\NewChapter\\uploads\\Life and Death in Shanghai.png'),
(11, 'Into the Wild', 'In April, 1992, a young man from a well-to-do family hitchhiked to Alaska and walked alone into the wilderness north of Mt. McKinley. His name was Christopher Johnson McCandless. He had given RM25,000 in savings to charity, abandoned his car and most of his possessions, burned all the cash in his wallet, and invented a new life for himself. Four months later, a party of moose hunters found his decomposed body. How McCandless came to die is the unforgettable story of Into the Wild.\r\n\r\nImmediately after graduating from college in 1991, McCandless had roamed through the West and Southwest on a vision quest like those made by his heroes Jack London and John Muir. In the Mojave Desert he abandoned his car, stripped it of its license plates, and burned all of his cash. He would give himself a new name, Alexander Supertramp, and, unencumbered by money and belongings, he would be free to wallow in the raw, unfiltered experiences that nature presented. Craving a blank spot on the map, McCandless simply threw away the maps. Leaving behind his desperate parents and sister, he vanished into the wild.', 'Jon Krakauer', 'Villard', 'Adventure, Biography, Travel', 1987, 'English', 10, '978-0-38-548680-4', 4, 1, 0, 0, 'Into the Wild.png', 'C:\\xampp\\htdocs\\NewChapter\\uploads\\Into the Wild.png'),
(12, 'Blue Highways', 'Hailed as a masterpiece of American travel writing, Blue Highways is an unforgettable journey along our nation\'s backroads.\r\n\r\nWilliam Least Heat-Moon set out with little more than the need to put home behind him and a sense of curiosity about those little towns that get on the map-if they get on at all-only because some cartographer has a blank space to fill: Remote, Oregon; Simplicity, Virginia; New Freedom, Pennsylvania; New Hope, Tennessee; Why, Arizona; Whynot, Mississippi.\r\n\r\nHis adventures, his discoveries, and his recollections of the extraordinary people he encountered along the way amount to a revelation of the true American experience.', 'William Moon', 'Fawcett Crest', 'Adventure', 1982, 'English', 6, '978-0-82-622026-4', 3, 0, 1, 0, 'Blue Highways.png', 'C:\\xampp\\htdocs\\NewChapter\\uploads\\Blue Highways.png'),
(13, 'Levels of the Game', 'It begins with the ball rising into the air for the initial serve and ends with the final point. McPhee provides a brilliant, stroke-by-stroke description while examining the backgrounds and attitudes which have molded the players\' games.', 'John McPhee', 'Straus and Giroux', 'Biography, Documentary, Sport', 1979, 'English', 5, '978-0-37-451525-3', 2, 0, 1, 0, 'Levels of the Game.png', 'C:\\xampp\\htdocs\\NewChapter\\uploads\\Levels of the Game.png'),
(14, 'The Last Shot', 'It ought to be just a game, but basketball on the playgrounds of Coney Island is much more than that. In The Last Shot, the aspirations of a few of the neighborhood\'s most promising players reveal that what they have going for them athletic talent, grace, and years of dedication may not be enough to defeat what\'s working against them: woefully inadequate schooling, family circumstances that are often desperate, and the slick, brutal world of college athletic recruitment.\r\n\r\nIncisively and compassionately written, The Last Shot introduces us to unforgettable characters and takes us into their world with an intimacy seldom seen in contemporary journalism. The result is a startling and poignant expose of inner-city life and the big business of college basketball.', 'Darcy Frey', 'Mariner Books', 'Documentary, Sport', 2004, 'English', 12, '978-0-61-844671-1', 3, 1, 0, 0, 'The Last Shot.png', 'C:\\xampp\\htdocs\\NewChapter\\uploads\\The Last Shot.png'),
(15, 'The Scholars', 'A masterpiece from the Ming dynasty, Wu Ching-tzu\'s The Scholars ranks with Dream of the Red Chamber, Journey to the West, and the Water Margin as one of the greatest classic novels of China. The Scholars is the first Chinese novel of its scope not to borrow any characters from history or legend and it is the first work of satiric realism to achieve an almost complete disassociation from the religious beliefs of the people. Departing from the impersonal tradition of Chinese fiction, Wu abandons such established narrative formulas as folk songs and poetic verse in favor of autobiographical experiences, descriptive realism, and characters modeled after his friends and relatives elements that combine to give this critique of the Confucian civil service system an unprecedented immediacy and humor.', 'Wu Ching-Tzu', 'Yunnan Peoples Publishing House', 'Documentary, History', 2005, 'Chinese', 5, '978-7-22-472836-5', 2, 0, 1, 0, 'The Scholars.png', 'C:\\xampp\\htdocs\\NewChapter\\uploads\\The Scholars.png'),
(16, 'Me Before You', 'Lou Clark knows lots of things. She knows how many footsteps there are between the bus stop and home. She knows she likes working in The Buttered Bun tea shop and she knows she might not love her boyfriend Patrick.\r\n\r\nWhat Lou does not know is she is about to lose her job or that knowing what is coming is what keeps her sane.', 'Jojo Moyes', 'Penguin Books', 'Adventure, Romance', 2012, 'English', 12, '978-0-71-817702-7', 3, 0, 0, 1, 'Me Before You.png', 'C:\\xampp\\htdocs\\NewChapter\\uploads\\Me Before You.png'),
(17, 'Charlie and the Chocolate Factory', 'Mr. Willy Wonka, the eccentric owner of the greatest chocolate factory in the world, has decided to open the doors of his factory to five lucky children and their parents. In order to choose who will enter the factory, Mr. Wonka devises a plan to hide five golden tickets beneath the wrappers of his famous chocolate bars. The search for the five golden tickets is fast and furious. Augustus Gloop, a corpulent child whose only hobby is eating, unwraps the first ticket, for which his town throws him a parade. Veruca Salt, an insufferable brat, receives the next ticket from her father, who had employed his entire factory of peanut shellers to unwrap chocolate bars until they found a ticket. Violet Beauregarde discovers the third ticket while taking a break from setting a world record in gum chewing. The fourth ticket goes to Mike Teavee, who, as his name implies, cares only about television.', 'Roald Dahl', 'Puffin Books', 'Adventure, Animation, Comedy, Fantasy', 2007, 'English', 10, '978-0-14-241031-8', 3, 1, 0, 0, 'Charlie and the Chocolate Factory.png', 'C:\\xampp\\htdocs\\NewChapter\\uploads\\Charlie and the Chocolate Factory.png'),
(18, 'The Cat in the Hat', 'When the Cat in the Hat steps in on the mat, Sally and her brother are in for a roller coaster ride of havoc and mayhem. The Cat can rescue them from a dull rainy day, but it means lots of thrills and spills along the way.\r\n\r\nThe wonderfully anarchic Cat in the Hat is one of the most popular characters in children fiction, and this book is ideal for budding readers to tackle on their own.', 'Dr. Seuss', 'HarperCollins', 'Adventure, Animation, Comedy', 2005, 'English', 10, '978-0-00-715844-7', 2, 1, 0, 0, 'The Cat in the Hat.png', 'C:\\xampp\\htdocs\\NewChapter\\uploads\\The Cat in the Hat.png'),
(19, 'The Martian', 'After a dust storm nearly kills him and forces his crew to evacuate while thinking him dead, Mark finds himself stranded and completely alone with no way to even signal Earth that he is alive and even if he could get word out, his supplies would be gone long before a rescue could arrive.\r\n\r\nChances are, though, he would not have time to starve to death. The damaged machinery, unforgiving environment, or plain-old human error are much more likely to kill him first.\r\n\r\nBut Mark is not ready to give up yet. Drawing on his ingenuity, his engineering skills and a relentless, dogged refusal to quit, he steadfastly confronts one seemingly insurmountable obstacle after the next. Will his resourcefulness be enough to overcome the impossible odds against him.\r\n\r\nNow, he is sure he will be the first person to die there.\r\n\r\nAfter a dust storm nearly kills him and forces his crew to evacuate while thinking him dead, Mark finds himself stranded and completely alone with no way to even signal Earth that he is alive and even if he could get word out, his supplies would be gone long before a rescue could arrive.\r\n\r\nChances are, though, he would not have time to starve to death. The damaged machinery, unforgiving environment, or plain-old human error are much more likely to kill him first.', 'Andy Weir', 'The Crown Publishing Group', 'Adventure, Fantasy, Sci-fi', 2011, 'English', 14, '978-0-55-341802-6', 1, 0, 0, 1, 'The Martian.png', 'C:\\xampp\\htdocs\\NewChapter\\uploads\\The Martian.png'),
(20, 'Dune', 'Set on the desert planet Arrakis, Dune is the story of the boy Paul Atreides, heir to a noble family tasked with ruling an inhospitable world where the only thing of value is the spice melange, a drug capable of extending life and enhancing consciousness. Coveted across the known universe, melange is a prize worth killing for...\r\n\r\nWhen House Atreides is betrayed, the destruction of his family will set the boy on a journey toward a destiny greater than he could ever have imagined. And as he evolves into the mysterious man, he will bring to fruition humankind most ancient and unattainable dream.', 'Frank Herbert', 'Chilton Books', 'Fantasy, Sci-fi', 1965, 'English', 5, '978-0-57-507518-4', 2, 0, 1, 0, 'Dune.png', 'C:\\xampp\\htdocs\\NewChapter\\uploads\\Dune.png'),
(21, 'The Hunger Games', 'The Hunger Games is a 2008 dystopian novel by the American writer Suzanne Collins. It is written in the perspective of 16-year-old Katniss Everdeen, who lives in the future, post-apocalyptic nation of Panem in North America.', 'Suzanne Collins', 'HarperCollins', 'Action, Mystery, Romance, Sci-fi', 2008, 'English', 23, '978-1-11-111111-3', 5, 0, 0, 1, 'The Hunger Games.png', 'C:\\xampp\\htdocs\\NewChapter\\uploads\\The Hunger Games.png'),
(22, 'Harry Potter and the Deathly Hallows', 'Harry Potter and the Deathly Hallows plays thoughtfully upon the standard Harry Potter formula that we\'ve all gotten used to over the course of the last six books – we begin with a menacing taste of what\'s to come (this time with a glimpse of what Voldemort and his Death Eaters are up to), find ourselves at Privet Drive at the end of the summer, and then make our way to Hogwarts. However, this version of the trajectory is thwarted at every point, as Rowling throws in curveball after curveball, shaking up all of our expectations.', 'J. K. Rowling', 'Bloomsbury', 'Action, Adventure, Fantasy', 2007, 'English', 20, '978-1-11-111111-9', 5, 0, 1, 0, 'Harry Potter and the Deathly Hallows.png', 'C:\\xampp\\htdocs\\NewChapter\\uploads\\Harry Potter and the Deathly Hallows.png'),
(23, 'Harry Potter and the Philosophers Stone', 'Ten-year-old Harry Potter is an orphan who lives in the fictional London suburb of Little Whinging, Surrey, with the Dursleys: his uncaring Aunt Petunia, loathsome Uncle Vernon, and spoiled cousin Dudley. The Dursleys barely tolerate Harry, and Dudley bullies him. One day Harry is astonished to receive a letter addressed to him in the cupboard under the stairs (where he sleeps). Before he can open the letter, however, Uncle Vernon takes it. Letters for Harry subsequently arrive each day, in increasing numbers, but Uncle Vernon tears them all up, and finally, in an attempt to escape the missives, the Dursleys go to a miserable shack on a small island. ', 'J. K. Rowling', 'Bloomsbury', 'Action, Adventure, Fantasy', 1997, 'English', 20, '978-1-11-111112-1', 3, 0, 1, 0, 'Harry Potter and the Philosophers Stone.png', 'C:\\xampp\\htdocs\\NewChapter\\uploads\\Harry Potter and the Philosophers Stone.png'),
(24, 'Harry Potter and the Chamber of Secrets', 'Harry Potter and the Chamber of Secrets begins when Harry is spending a miserable summer with his only remaining family, the Dursleys. During a dinner party hosted by his uncle and aunt, Harry is visited by Dobby, a house-elf. Dobby warns Harry not to return to Hogwarts, the magical school for wizards that Harry attended the previous year. Harry politely disregards the warning, and Dobby wreaks havoc in the kitchen, infuriating the Dursleys. The Dursleys angrily imprison Harry in his room for the rest of the summer. Luckily, Harry\'s friend Ron Weasley steals Harry away in a flying car, and Harry happily spends the rest of the summer at the Weasley home.', 'J. K. Rowling', 'Bloomsbury', 'Action, Adventure, Fantasy', 1998, 'English', 20, '978-1-11-111112-2', 5, 0, 1, 0, 'Harry Potter and the Chamber of Secrets.png', 'C:\\xampp\\htdocs\\NewChapter\\uploads\\Harry Potter and the Chamber of Secrets.png'),
(25, 'Harry Potter and the Prisoner of Azkaban', 'Harry Potter and the Prisoner of Azkaban opens on the night before Harry\'s thirteenth birthday, when he receives gifts by Owl Post from his friends at school. The next morning at breakfast, Harry sees on television that a man named Black is on the loose from prison. At this time, Aunt Marge comes to stay with the Dursleys, and she insults Harry\'s parents numerous times. Harry accidentally causes her to inflate. Harry leaves the Dursley\'s house and is picked up by the Knight Bus, but only after an alarming sighting of a large, black dog. The Knight Bus drops Harry off at Diagon Alley, where he is greeted by Cornelius Fudge, the Minister of Magic.', 'J. K. Rowling', 'Bloomsbury', 'Action, Adventure, Fantasy', 1999, 'English', 20, '978-1-11-111112-3', 5, 0, 1, 0, 'Harry Potter and the Prisoner of Azkaban.png', 'C:\\xampp\\htdocs\\NewChapter\\uploads\\Harry Potter and the Prisoner of Azkaban.png'),
(26, 'Harry Potter and the Goblet of Fire', 'The story begins fifty years before the present day, with a description of how the Riddle family was mysteriously killed at supper, and their groundsman, Frank Bryce, was suspected of the crime, then declared innocent. Frank Bryce, now an elderly man, wakes in the night to see a light in the window of the abandoned Riddle House. He investigates and overhears Voldemort and Wormtail plotting to kill a boy named Harry Potter. Voldemort takes note of him and kills him on the spot. Harry Potter wakes up in the night with a throbbing pain in the scar Voldemort gave him. He worries that Voldemort is nearby, and he writes to Sirius Black, his godfather, mentioning the pain in his scar.\n\n', 'J. K. Rowling', 'Bloomsbury', 'Action, Adventure, Fantasy', 2000, 'English', 20, '978-1-11-111112-4', 5, 0, 1, 0, 'Harry Potter and the Goblet of Fire.png', 'C:\\xampp\\htdocs\\NewChapter\\uploads\\Harry Potter and the Goblet of Fire.png'),
(27, 'Harry Potter and the Order of the Phoenix', 'Harry Potter is spending another tedious summer with his dreadful Aunt Petunia and Uncle Vernon when a group of evil spirits called “dementors” stage an unexpected attack on Harry and his cousin Dudley. After using magic to defend himself, Harry is visited by a group of wizards and whisked off to number twelve, Grimmauld Place, London. Number twelve is the home of Harry’s godfather, Sirius Black, and the headquarters of the Order of the Phoenix. The Order is a group of wizards, led by Hogwarts headmaster Albus Dumbledore, dedicated to fighting evil Lord Voldemort and his followers. The Order is forced to operate in secrecy, outside of the jurisdiction of the Ministry of Magic, which is headed by the dense and corrupt Cornelius Fudge. Fudge refuses to believe that Lord Voldemort has returned.', 'J. K. Rowling', 'Bloomsbury', 'Action, Adventure, Fantasy', 2003, 'English', 20, '978-1-11-111111-8', 5, 0, 1, 0, 'Harry Potter and the Order of the Phoenix.png', 'C:\\xampp\\htdocs\\NewChapter\\uploads\\Harry Potter and the Order of the Phoenix.png'),
(28, 'Harry Potter and the Half-Blood Prince', 'Lord Voldemort has returned to power, and his wrath has been felt in both the Muggle and Wizarding worlds. Severus Snape, long considered an enemy of Voldemort and a member of Dumbledore’s anti-Voldemort coalition, the Order of the Phoenix, meets with Narcissa Malfoy, mother of Draco and wife of Lucius, an imprisoned Death Eater. Snape makes an Unbreakable Vow to Narcissa, promising to protect her son, Draco.', 'J. K. Rowling', 'Bloomsbury', 'Action, Adventure, Fantasy', 2005, 'English', 20, '978-1-11-111111-7', 5, 0, 1, 0, 'Harry Potter and the Half-Blood Prince.png', 'C:\\xampp\\htdocs\\NewChapter\\uploads\\Harry Potter and the Half-Blood Prince.png'),
(29, 'To Kill a Mockingbird', 'To Kill a Mockingbird is a novel by the American author Harper Lee. It was published in 1960 and was instantly successful. In the United States, it is widely read in high schools and middle schools. To Kill a Mockingbird has become a classic of modern American literature, winning the Pulitzer Prize. The plot and characters are loosely based on Lee\'s observations of her family, her neighbors and an event that occurred near her hometown of Monroeville, Alabama, in 1936, when she was ten.', 'Harper Lee', 'J. B. Lippincott n\' Co.', 'Adventure, Fantasy, Horror', 1960, 'English', 30, '978-0-44-631078-9', 7, 0, 0, 1, 'To Kill a Mockingbird.png', 'C:\\xampp\\htdocs\\NewChapter\\uploads\\To Kill a Mockingbird.png'),
(30, 'Gullivers Travels', 'Gulliver\'s Travels is a four-part prose travelogue, narrated by the fictitious persona of Lemuel Gulliver, who tells the story of his extensive global voyages, the places he has been and the people (and other creatures) he met. The satire was first published in 1726 under the title Travels into Several Remote Nations of the World \'By Lemuel Gulliver\'.', 'Jonathan Swift', 'Benjamin Motte', 'Action', 1800, 'English', 22, '978-0-94-667465-7', 8, 0, 0, 1, 'Gullivers Travels.png', 'C:\\xampp\\htdocs\\NewChapter\\uploads\\Gullivers Travels.png'),
(31, 'Gone Girl', 'Gone Girl is a 2012 crime thriller novel by American writer Gillian Flynn. It was published by Crown Publishing Group in June 2012. The novel was popular and made the New York Times Best Seller list. The sense of suspense in the novel comes from whether Nick Dunne is responsible for the disappearance of his wife Amy.', 'Gillian Flynn', 'Crown Publishing Group', 'Action, Horror', 2012, 'English', 24, '978-0-30-758836-4', 6, 1, 0, 0, 'Gone Girl.png', 'C:\\xampp\\htdocs\\NewChapter\\uploads\\Gone Girl.png'),
(32, 'Ready Player One', 'Ready Player One is a 2011 science fiction novel, and the debut novel of American author Ernest Cline. The story, set in a dystopia in 2045, follows protagonist Wade Watts on his search for an Easter egg in a worldwide virtual reality game, the discovery of which would lead him to inherit the game creator\'s fortune.', 'Ernest Cline', 'Crown Publishing Group', 'Fantasy, Sci-fi', 2011, 'English', 27, '978-1-52-476328-2', 4, 1, 0, 0, 'Ready Player One.png', 'C:\\xampp\\htdocs\\NewChapter\\uploads\\Ready Player One.png'),
(33, 'Red Sorghum', 'Red Sorghum: A Novel of China or Red Sorghum Clan is a Chinese language novel by Mo Yan. Its five parts were published serially in various magazines in 1986 and republished together as a single novel in 1987. It was Mo\'s first novel and remains one of his best-known works.', 'Mo Yan', 'Hong Fan', 'Adventure, Fantasy', 1942, 'Chinese', 24, '978-0-14-016854-9', 5, 0, 0, 1, 'Red Sorghum.png', 'C:\\xampp\\htdocs\\NewChapter\\uploads\\Red Sorghum.png'),
(34, 'Salina', 'Novel mengenai seorang perempuan bernama Salina yang didorong kemiskinan untuk mencari kerja sebagai pelayan di Singapura dan Tanah Melayu (Malaysia) pada tahun 50-an.', 'A. Samad Said', 'Wira Bukit Sdn. Bhd', 'Fantasy', 1961, 'Bahasa Melayu', 23, '978-9-67-430256-6', 4, 1, 0, 0, 'Salina.png', 'C:\\xampp\\htdocs\\NewChapter\\uploads\\Salina.png');

-- --------------------------------------------------------

INSERT INTO `donations` (`donationID`, `status`, `userID`, `bookTitles`, `donationMethod`, `donationStreet`, `donationCity`, `donationState`, `donationPostcode`, `donationDate`, `donationTime`) VALUES
(1, 'Complete', 'U006', 'The Hobbit, Crazy Rich Asians', 'Drop By', '37, Jalan PJU 5/10, Seksyen 13, Kota Damansara', 'Petaling Jaya', 'Selangor', 47810, '2022-10-12', '11:50:00'),
(2, 'Complete', 'U005', 'On Food and Cooking, Into the Wild, Me Before You', 'Mail', 'Lot 107, Level 1, Kuala Lumpur\r\nCity Centre', 'Kuala Lumpur', 'Selangor', 50088, '2022-10-19', '11:30:00'),
(3, 'Incomplete', 'U010', 'The Hunger Games, Frankenstein', 'Collect', '18, Jalan PJU 1A/25, Damansara Kim', 'Petaling Jaya', 'Selangor', 47301, '2022-11-27', '14:00:00');

-- --------------------------------------------------------


INSERT INTO `orders` (`orderID`, `status`, `bookIDs`, `userID`, `orderTotal`, `paymentMethod`, `orderDate`, `deliveryOption`, `deliveryStreet`, `deliveryCity`, `deliveryState`, `deliveryPostcode`, `deliveryDate`, `deliveryTime`) VALUES
(1, 'Complete', 'B001, B005', 'U004', '19.00', 'Credit Card', '2022-10-06', 'Self Pick-up', '12, Jalan USJ 11/4b, USJ 11', 'Subang Jaya', 'Selangor', 47620, '2022-10-07', '11:45:00'),
(2, 'Complete', 'B003, B008, B010', 'U009', '40.00', 'Touch n Go eWallet', '2022-10-10', 'Standard Courier', '5, Jalan PJU 1B/25, Ara Damansara', 'Petaling Jaya', 'Selangor', 47301, '2022-10-12', '15:45:00'),
(3, 'Complete', 'B015, B020', 'U007', '15.00', 'GrabPay', '2022-10-21', 'Standard Courier', '18, Jalan Kenyalang 15/3c, Kota Damansara', 'Petaling Jaya', 'Selangor', 52100, '2022-10-24', '12:00:00'),
(4, 'Complete', 'B006', 'U012', '13.00', 'Touch n Go eWallet', '2022-10-30', 'Self Pick-up', '37, Jalan PJU 5/10, Seksyen 13, Kota Damansara', 'Petaling Jaya', 'Selangor', 47810, '2022-10-31', '14:30:00'),
(5, 'Incomplete', 'B002, B004, B009', 'U001', '34.00', 'Credit Card', '2022-11-18', 'Standard Courier', '20, Jalan 1B/21, USJ 17', 'Subang Jaya', 'Selangor', 47620, '2022-11-29', '09:00:00'),
(6, 'Incomplete', 'B017, B018', 'U011', '20.00', 'Touch n Go eWallet', '2022-11-19', 'Self Pick-up', 'Lot 107, Level 1, Kuala Lumpur\r\nCity Centre', 'Kuala Lumpur', 'Selangor', 50088, '2022-11-28', '10:15:00');

-- --------------------------------------------------------


INSERT INTO `users` (`userID`, `fname`, `lname`, `contactNum`, `username`, `email`, `password`, `role`) VALUES
(1, 'John', 'Doe', '+6012-1234567', 'john_doe', 'john_doe@gmail.com', '$2y$10$NQy63YGFP6UlP2UOou4OtOMK1mMJNl4.VJzMDnizighUgyg0VcK32', 2),
(2, 'Jia Ying', 'Tan', '+6019-0243789', 'tan_jiaying', 'tanjiaying@gmail.com', '$2y$10$iWsCprY0x0QdDj90Gf5yKeCzk6sROUY4/7YBZSEw.5nk6.L9qpYIi', 1),
(3, 'Darren', 'Siew', '+6018-2342736', 'darren_siew', 'darrensiew@gmail.com', '$2y$10$rsTyi0e9ITuw/BxXvAqJGeHCWi655lWqCloZoR4RdOnsYzKNqa.HK', 1),
(4, 'Mary', 'Jane', '+6011-12345678', 'mary_jane', 'maryjane@gmail.com', '$2y$10$3oUUzBOkQlQQ.eziivYmT.QhN8KVZzgUk8k51k1nf0krtTGzcPYiu', 2),
(5, 'Charles', 'Smith', '+6019-2938467', 'charles_smith', 'charlessmith@yahoo.com', '$2y$10$k/QFc52Rq1d54c25xJBCg.nKWnEfAc9D9TDGD7zAWEt/2p7CQLnTm', 2),
(6, 'Mei Yee', 'Lim', '+6018-1237645', 'meiyee_lim', 'meiyeelim@hotmail.com', '$2y$10$dV/Z7WYz9PHOgsEyv071Z.OEaDLZb1imRQgfIIadLl9R1I7ldbY2O', 2),
(7, 'Edward', 'Leong', '+6014-2358926', 'edward_leong', 'edwardleong@gmail.com', '$2y$10$lYMs3CYfuBWigaU4zFfig.foQztdyUd6uB10Zo/Ui.gnZMH/keJnm', 2),
(8, 'Xiao Ai', 'Wong', '+6011-28374625', 'xiaoai_wong', 'xiaoaiwong@hotmail.com', '$2y$10$OmDDApy90dZeQ4J2lWvZeu9XK/UWunZYa8UhkdoppO6hoQNO4K2vO', 2),
(9, 'Jason', 'Lee', '+6012-2345672', 'jason_lee', 'jasonlee@yahoo.com', '$2y$10$G27vNlLxiAOkfpZa7VHuEuiF/5AgLnAK537kZu1Pz0CrSGKKY9bU.', 2),
(10, 'Yuan Yee', 'Lee', '+6019-2345617', 'yuenyee_lee', 'yuanyeelee@yahoo.com', '$2y$10$okKQZl9/CluPLrtKv1OI/Oeb68lCguDH7sF.h.mU9LtZRRprua1Wq', 2),
(11, 'Jennifer', 'See', '+6018-1392635', 'jennifer_see', 'jennifersee@gmail.com', '$2y$10$f/tnO465ewiWFv.gtNymCOnnaBWFI4Y9MMQW3B/nQse78gbyMyMti', 2),
(12, 'Bryan', 'Wong', '+6012-3427835', 'bryan_wong', 'bryanwong12@gmail.com', '$2y$10$3OavAFYDtRWfQB1/Shha6uG6o9dVwWsT0iHBOv62vOAbQqUaxkXAS', 2),
(13, 'Joe Yi', 'Ooi', '+6011-12637827', 'joeyi_ooi', 'joeyi_ooi@yahoo.com', '$2y$10$FnfDWJlE7uvxDrMPUioN6OJk6ShBGULwAJEOazyXIx9nbQl1EFBae', 2),
(14, 'Xin Le', 'Lim', '+6014-2349827', 'xinle13', 'xinle_lim@gmail.com', '$2y$10$9.YgnZxdRp3tDSHIfvK8qeeZaXBiwAxG6AuVwY88Z96WrFn49GC4S', 2),
(15, 'Jun Hao', 'Wong', '+6019-8725637', 'jun_hao', 'junhaowong@hotmail.com', '$2y$10$Gw0gvrDkqx4JyWfFSWS0HOaJuDvvjNNKf8Ybkfut2UwqkpCOlplu6', 2),
(16, 'Cai Ni', 'Wu', '+6013-2341234', 'wu_caini', 'cainiwu@gmail.com', '$2y$10$iENJjOX8MMxYmlf.oDiI7.wE9Eyc7zNJdc.0bRlbM8cA.cbL9Vofe', 2),
(17, 'Yu Meng', 'Chai', '+6012-4561837', 'chai_yumeng', 'yumengchai@yahoo.com', '$2y$10$CmfstxXrk59UeUAft4P1d.BGVBT2QXzovSq28YveuLflFAq0rBlyq', 2);